const SET_IMAGE_FILE_NAME = 'SET_IMAGE_FILE_NAME';
const SET_IMAGE_HEIGHT = 'SET_IMAGE_HEIGHT';
const SET_IMAGE_WIDTH = 'SET_IMAGE_WIDTH';

const APPEND_IMAGE = 'APPEND_IMAGE';
const PREPEND_IMAGE = 'PREPEND_IMAGE';
const SET_IMAGES = 'SET_IMAGES';

const SET_PREVIEW_IMAGE_URL = 'SET_PREVIEW_IMAGE_URL';

const SET_THEME_COLOR = 'SET_THEME_COLOR';

export {
  APPEND_IMAGE,
  PREPEND_IMAGE,
  SET_IMAGE_FILE_NAME,
  SET_IMAGE_HEIGHT,
  SET_IMAGE_WIDTH,
  SET_IMAGES,
  SET_PREVIEW_IMAGE_URL,
  SET_THEME_COLOR,
};
